-- Rollback initial schema

DROP TABLE IF EXISTS "schema_migrations" CASCADE;
DROP TABLE IF EXISTS "meta" CASCADE;
DROP TABLE IF EXISTS "instance" CASCADE;
DROP TABLE IF EXISTS "emoji" CASCADE;
DROP TABLE IF EXISTS "access_token" CASCADE;
DROP TABLE IF EXISTS "following" CASCADE;
DROP TABLE IF EXISTS "note_reaction" CASCADE;
DROP TABLE IF EXISTS "poll" CASCADE;
DROP TABLE IF EXISTS "note" CASCADE;
DROP TABLE IF EXISTS "user_keypair" CASCADE;
DROP TABLE IF EXISTS "user_profile" CASCADE;
DROP TABLE IF EXISTS "drive_file" CASCADE;
DROP TABLE IF EXISTS "drive_folder" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

DROP TYPE IF EXISTS followers_visibility_enum;
DROP TYPE IF EXISTS following_visibility_enum;
DROP TYPE IF EXISTS note_visibility_enum;
